# Generated by Django 3.0.2 on 2020-01-21 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, default='192.168.33.11', max_length=13, null=True)),
                ('username', models.CharField(blank=True, default='ADMIN', max_length=25, null=True)),
                ('password', models.CharField(blank=True, default='ADMIN', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.FloatField(blank=True, null=True)),
                ('x2', models.FloatField(blank=True, null=True)),
                ('y1', models.FloatField(blank=True, null=True)),
                ('y2', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, choices=[(0, 'Hard hat'), (1, 'Safety Vest'), (2, 'Googles'), (3, 'Gloves'), (4, 'Shoes'), (5, 'Restricted Entry'), (6, 'Mobile Phone Usage'), (7, 'Fire'), (8, 'Oil Spill')], max_length=2, null=True)),
                ('event_category', models.CharField(blank=True, choices=[(1, 'Restrictions'), (0, 'Safety')], max_length=2, null=True)),
                ('model_name', models.CharField(blank=True, max_length=20, null=True)),
                ('model_version', models.CharField(blank=True, max_length=10, null=True)),
                ('confidence_score', models.BooleanField(blank=True, null=True)),
                ('event_state', models.BooleanField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_coordinates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Detections.Event_Coordinates')),
            ],
        ),
    ]
