# Generated by Django 3.0.3 on 2020-03-03 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Detections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='camera_id',
            field=models.CharField(blank=True, default='453', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ou_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Detections.Camera'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.IntegerField(blank=True, choices=[(1, 'Restrictions'), (0, 'Safety')], null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_coordinates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='Detections.Event_Coordinates'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.IntegerField(blank=True, choices=[(0, 'Hard hat'), (1, 'Safety Vest'), (2, 'Googles'), (3, 'Gloves'), (4, 'Shoes'), (5, 'Restricted Entry'), (6, 'Mobile Phone Usage'), (7, 'Fire'), (8, 'Oil Spill')], null=True),
        ),
    ]
